name: Build Rust/Diesel/Posgtres

on:
  push:
    branches:
      - "main"

env:
  RUST_VERSION: 1.64

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./rust/diesel-build/postgres/armv7
          build-args:
            RUST_VERSION: ${RUST_VERSION}
          tags: |
            ghcr.io/j-be/rust-diesel-postgres:${RUST_VERSION}-armv7
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}